### ISSUE TITLE
Provide hooks to when Index has loaded

### ISSUE THREAD

**Issue by patricksimonian** [humanseelabs/gatsby-plugin-lunr#11]
I'm getting a race condition as it takes some time to fetch the index which is causing my app to fail on **page refresh**. Interestingly enough I would have thought the browser would have cached the index file. But it appears not to have. 

To clarify what I'm trying to do..

```javascript

componentDidMount() {
// check url for query params '?q=foo'
// if query exists attempt to search index for 'foo'
// run index search routine
}
```

I get an error
`TypeError: Cannot read property 'en' of undefined`

which makes sense as ```window.__LUNR__``` doesn't exist yet. 

It appears that this code found within the libraries `gatsby-browser.js` is where we find a race condition.
```javascript
fetch(__PATH_PREFIX__ + "/" + filename).then(function (response) {
        return response.json();
    }).then(function (fullIndex) {
        window.__LUNR__ = (0, _keys2.default)(fullIndex).reduce(function (prev, key) {
            return (0, _assign2.default)({}, prev, (0, _defineProperty3.default)({}, key, {
                index: lunr.Index.load(fullIndex[key].index),
                store: fullIndex[key].store
            }));
        }, {});
    })
```

again i'm not too sure why the json file is not caching or atleast slow to load on subsequent requests, but perhaps we can define the __LUNR__ object and allow the ability to bind an event to it that gets fired when the index is loaded.

## Work around

For now, since this appears to be an issue on *page refreshes* i'm resorting to working around it with a race condition check (set timeout) which is less then ideal :(

**Comment by magnusarinell** [comment]
Could be good to document this perhaps so that one doesn't have to look through closed issues to find the solution :)
