### ISSUE TITLE
integrate with lunr-chinese

### ISSUE THREAD

**Issue by wulucxy** [humanseelabs/gatsby-plugin-lunr#16]
Hi，how can i integrate with [lunr-chinese](https://github.com/Wiredcraft/lunr-chinese)，so I can use chinese language。

or do you guys has other suggestion?

**Comment by deemaagog** [comment]
Hi
you have to:
1)  make this package compatible with latest Lunr if it isn't
2) create a PR to https://github.com/MihaiValentin/lunr-languages
