### ISSUE TITLE
gatsby-plugin-lunr > 1.4 causes build error in my Gatsby V1 project

### ISSUE THREAD

**Issue by benlavalley** [humanseelabs/gatsby-plugin-lunr#22]
Getting this error with gatsby develop and a lengthier error with trace in gatsby build in my Gatsby V1 project:

```
 ERROR  Failed to compile with 1 errors                                                                                                 08:43:59

This dependency was not found:

* fs in ./~/gatsby-plugin-lunr/gatsby-node.js
```
After some troubleshooting I found that the changes introduced in 1.5.0 were causing the problem and I locked gatsby-plugin-lunr at 1.4.0 in my package.json.

I know, I know... I should just update my project to Gatsby V2 where I'm assuming this won't happen. Soon :) 

I've obviously resolved the problem so I'm mainly just posting this to assist anyone who might run into the same issue.

**Comment by deemaagog** [comment]
Thank you for pointing that!
