### ISSUE TITLE
Accessing Tokenizer

### ISSUE THREAD

**Issue by azdanov** [humanseelabs/gatsby-plugin-lunr#4]
Is there a way to access lunr's tokenizer?

I'm trying to create an autosuggest, and token results are too mangled to display for end users.

__EDIT:__

What I'd like to accomplish is integrate this plugin with [downshift](https://github.com/paypal/downshift) and [match-sorter](https://github.com/kentcdodds/match-sorter) for autosuggestion while typing.

**Comment by deemaagog** [comment]
Which mangled results are you talking about? Could you elaborate?

**Comment by azdanov** [comment]
On my (WIP) blog https://azdanov.js.org/blog. If you click on search, it will display all the tokens that can be used for searching. And lots of results are truncated at the end. 

For example `pretty` -> `pretti`, `dummy` -> `dummi`, `information` -> `inform`.

I understand that this happens to facilitate searching. But in my use case, I'd like a different behavior.

_P.S. This is my first time working with lunr, and searching on a website in general._

**Comment by deemaagog** [comment]
Lunr.js provides an opportunity to customize tokenization through the plugin.  Will this be enough for you?

```js
var myTokenizerPlugin = function () {
  var tokenizer = function (obj) {
    // implementation
  }

  lunr.tokenizer.registerFunction(tokenizer, 'myTokenizer')

  this.tokenizer(tokenizer)
}

var idx = lunr(function () {
  this.use(myTokenizerPlugin)
})
```

**Comment by azdanov** [comment]
Thanks for the information!

How and where would I plug this in? Since I'm not accessing `lunr` directly in my code.

Currently, I grab the search keys from `window.__LUNR__.en.index.invertedIndex` and they already exist in such a state.

__EDIT:__

Should I use this `const lunrIndex =  window.__LUNR__[this.props.lng];` to set the plugin?

For example:

```js
var idx = window.__LUNR__[this.props.lng](function () {
  this.use(myTokenizerPlugin)
})
```

**Comment by deemaagog** [comment]
At the moment this is impossible, I'll add an option next week

**Comment by azdanov** [comment]
Awesome! Thanks for clarifying the issue.
