### ISSUE TITLE
Fetching the search index does not recognize the path prefix

### ISSUE THREAD

**Issue by Jerjerzanne** [humanseelabs/gatsby-plugin-lunr#5]
When building for production for gh-pages, I noticed that the `search_index.json` was fetched without the path prefix I had set in my `modules.exports`. I can add the prefix manually, which solves the issue, but it would be nice if the plugin could detect it.  
 I have no experience with plugin development for Gatsby, but do you think it would be hard to query for the path prefix and add it to the fetch call?   

This is what would need to be queried:
```
{
  site {
    pathPrefix
  }
}
```  
The path prefix should be added in the fetch call:
```
exports.onClientEntry = function (args, _ref) {
    var languages = _ref.languages;

    enhanceLunr(lunr, languages);
    fetch(pathPrefix + '/search_index.json').then(function (response) {
```
Either way, thank you for your time and your plugin is great!

**Comment by deemaagog** [comment]
Done
