### ISSUE TITLE
`gatsby-plugin-lunr` does not generate index on `gatsby develop`

### ISSUE THREAD

**Issue by ryaninvents** [humanseelabs/gatsby-plugin-lunr#7]
When I run `gatsby develop`, I notice that the Lunr index is not being built. I've had to run `gatsby build` to update the index, then restart my `gatsby develop` process in order to work on the search component.

**Comment by deemaagog** [comment]
This is because the plugin uses an api method onPostBuild that is called only on build, not development

**Comment by ryaninvents** [comment]
Oh cool! I'll play around with `onPreInit`/`onCreatePage` and see if I can make a PR. Might not get to it for a bit though

**Comment by deemaagog** [comment]
hmm... onPostBootstrap seems to be the right replacement.

**Comment by LekoArts** [comment]
Hi 👋 Any progress on this?

**Comment by deemaagog** [comment]
It should work now

**Comment by pauleveritt** [comment]
However it doesn't appear to reflect changes in content. You have to delete .cache and restart ``gatsby develop`` to see any changes.
