### ISSUE TITLE
Add possibility to add version number on search_index.json to prevent caching

### ISSUE THREAD

**Issue by rawbert** [humanseelabs/gatsby-plugin-lunr#9]
It would be awesome to **add config parameter as a function** in gatsby-plugin-lunr config on how to resolve version number.

Then make sure that the plugin's **gatsby-node.js** writes the file with that version number appended to file name and also that the plugin's **gatsby-browser.js** make use of that version-number when it fetches the file.

This is to prevent the file from being cached to hard by the client.

Thanks for a great plugin!

**Comment by deemaagog** [comment]
I'd suggest an optional custom filename
options: {
  filename: 'search_index.json?v='+random()
}
what do you think?

**Comment by rawbert** [comment]
Yeah that sounds reasonable and easy to maintain. Default is search_index.json and then you have the option to set it to whatever you like, if you want a version or not. Thumbs up 👍

**Comment by deemaagog** [comment]
#10

**Comment by rawbert** [comment]
Thats awesome! Will try it out

**Comment by deemaagog** [comment]
Closing this. Feel free to repoen if necessary.
